config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tweets#index'
  resources :tweets, only:[:index, :new, :create]
  resources :categories, only:[:index, :create, :destroy]
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_paranoid
  # アソシエーション
  belongs_to :user
  has_many :tweets
  # バリデーション
  with_options presence: true do
    validates :task,
              length: { maximum: 10 } 
  end
   
  
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  # アソシエーション
  belongs_to :user
  belongs_to :category, -> { with_deleted }
  # バリデーション
  with_options presence: true do
    validates :text
    validates :hour_time,
              format: { with: /\A[0-9]+(\.[0-9]+)?\z/}
    validates :category_id
  end
    # 一つ目の選択「--」の時は保存できないようにする
    # validates :category_id, numericality: { other_than: 1 } 
end

app/models/user.rb
class User < ApplicationRecord
#   アソシエーション
  has_many :tweets
  has_many :categories
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  with_options presence: true do
    validates :nickname, length: { maximum: 8 }
    validates :email
    validates :password, length: { minimum: 6 },
                        format: { with: /\A(?=.*?[a-z])[a-z\d]{6,32}+\z/ }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:destroy]
  
  def create
    @category = Category.new(category_params)
    @category.save
    @categories = current_user.categories
  end

  def destroy
     @category.destroy
  end

  private
  def category_params
    params.require(:category).permit(:task).merge(user_id: current_user.id)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :move_to_sign_in, except: [:index]

  def index
    @study_user = Tweet.where(user_id: current_user.id)  # ログイン中のユーザーの取得
    @study_hour = @study_user.sum(:hour_time)            # ログイン中のユーザーの総学習時間を取得
    # @user_runking = User.joins(:tweets).select('users.*, tweets.text').group("id").order("count(tweets.user_id) DESC").limit(5)
    query = "SELECT users.`nickname`, SUM(tweets.`hour_time`) 
             FROM tweets
             JOIN users
             ON tweets.user_id = users.id
             GROUP BY users.`nickname`
             LIMIT 5"
    @user_runking = Tweet.find_by_sql(query)               #学習時間が多いトップ５取得
    @tweets = Tweet.includes(:user).order("created_at DESC").page(params[:page]).per(10)                                  # ツイートの取得
    if user_signed_in?
      @categories = current_user.categories
    end
    @category = Category.new
  end

  def new
    @tweet_category = Tweet.new
    @categories = current_user.categories
  end

  def create
    @tweet_category = Tweet.new(tweet_category_params)
      if @tweet_category.save
        redirect_to  controller: :tweets, action: :index
      else 
        render action: :new
      end
  end

  def move_to_sign_in
    unless user_signed_in?
      redirect_to "/users/sign_in"
    end
  end
  private
  def tweet_category_params
    params.require(:tweet).permit(:text, :hour_time, :category_id).merge(user_id: current_user.id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_sign_in, only: [:show]


  def show
    @user = current_user                      #ログイン中のユーザー情報の取得
    @tweets = current_user.tweets             #ログイン中のユーザーのツイートを取得
    @user_tweets = @tweets.sum(:hour_time)    #ログイン中ユーザーの総学習時間を取得
    @tweets_count = @tweets.count             #ログイン中ユーザーの総投稿数
    @chart = { "2020-01-01" => 100, "2020-01-02" => 80, "2020-01-03" => 110, "2020-01-04" => 130, "2020-01-05" => 90 }

  end

  def move_to_sign_in
    unless user_signed_in?
      redirect_to "/users/sign_in"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_index.html.erb
<div class="task-lists">
  <% if user_signed_in? %>
    <% @categories.each do |category| %>
      <ul class="task-lists" id="category-<%= category.id %>">
        <li class="task"><i class="fa fa-caret-right"></i><%= category.task %></li>
        <li>
          <%= link_to category_path(category.id), method: :delete, remote: true, class:'category-destroy' do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        </li> 
      </ul>
    <% end %>
  <% end %>
</div>

app/views/categories/_new.html.erb
<%# タスク入力フォーム %>
<div class="task-contents">
    <%= form_with model: @category, id: 'new_tasks', class: 'new_tasks' do |f| %>
     <div class="task-field">
       <%= f.text_field :task %>
     </div>
     <div class="task-actions">
       <%= f.submit "+" %>
     </div>
    <% end %>
</div>

app/views/categories/create.js.erb
(function(){
  document.querySelector(".task-lists").innerHTML =  '<%= j(render 'categories/index', categories: @categories) %>'
  document.querySelector("#category_task").value = ''
})();
  

  

app/views/categories/destroy.js.erb
(function(){
  document.querySelector("#category-<%= @category.id %>").remove()
})();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Futures</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "hello_vue" %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.4.1/jquery.jscroll.min.js"></script>
    <%# = stylesheet_pack_tag 'hello_vue' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/_main_view.html.erb
<head>
  <link href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" rel="stylesheet">
  
  <%# <script src="//unpkg.com/jscroll/dist/jquery.jscroll.min.js"></script> %>
  <%# <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script> %>
</head>

<div class="top-header">
  <i class="far fa-paper-plane fa-2x"></i>
  <h1 class="header-title">futures</h1>
  <label class="toggle" for="open"><i class="fas fa-crown" aria-hidden="true"></i>
    </label>
    <input id="open" type="checkbox">
    <div id="menu">
      <nav>
        <div class="runking-best-contents">
          <form method="get" action="#" class="search_container">
            <input type="text" size="25" placeholder="　キーワード検索">
            <input type="submit" value="検索">
          </form>
        </div>
        <<div class="best_user">
          <div class="box-title">積み上げランキング</div>
          <% @user_runking.each_with_index do |user,i| %>
            <p class="runking-list"><span><%= "#{i+1}位 #{user.nickname}" %></span></p>
          <% end %>
        </div>
        <ul class="follow-me">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
            <ul class="follow-me">
              <li><a href="https://twitter.com"></a></li>
              <li><a href="https://www.facebook.com"></a></li>
              <li><a href="https://plus.google.com"></a></li>
              <li><a href="https://www.youtube.com"></a></li>
              <li><a href="https://www.tumblr.com"></a></li>
           </ul>
      </nav>
    </div>
  <ul class="header-list">
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "destroy" %></li>
    <%= link_to "マイページ", user_path(:user) %> 
  </ul>

  <label class="toggles" for="opens"><i class="fas fa-user-circle" aria-hidden="true"></i>
    </label>
    <input id="opens" type="checkbox">
    <div id="menus">
      <nav>
          <% if user_signed_in? %>
          <ul class="user-info">
            <li><%= link_to current_user.nickname, "#", class: "user-nickname" %> </li>
            <li>画像</li>
          </ul>
          <% end %>
          <div class="record-view">
            <div class="all_time">
              <p class="study-log">あなたの総学習時間は、、、</p>
              <p class="time"><%= @study_hour %>時間です<p>
            </div>
          </div>
          <div class="task-contents">
            <%= form_with model: @category, id: 'new_tasks', class: 'new_tasks' do |f| %>
              <div class="task-field">
                <%= f.text_field :task %>
              </div>
              <div class="task-actions">
                <%= f.submit "+" %>
              </div>
            <% end %>
          </div>
          <div class="task-lists">
            <% if user_signed_in? %>
              <% @categories.each do |category| %>
                <ol class="task-list">
                  <li><i class="fa fa-caret-right"></i><%= category.task %></li>
                  <li>
                    <%= link_to category_path(category.id), method: :delete, remote: true, class:'category-destroy' do %>
                      <i class="far fa-trash-alt"></i>
                    <% end %>
                  </li>
                </ol>
              <% end %>
            <% end %>
          </div>
          <div class="design-btn">
            <a href="/tweets/new" class="btn-square-little-rich">積み上げる</a>
          </div>
      </nav>
    </div>

  
</div>

<div class="center-box">
  <div class="home-logo">
    <p><i class="fas fa-home fa-2x"></i></p>
    <p class="home-text">ホーム</p>
  </div>
</div>
<div class="top-contents">
  <div class="jscroll">
    <div class="tweets-contents">
      <% @tweets.each do |tweet| %>
      <ul class="tweets-list">
        <p>
          <i class="fas fa-user-circle"></i>
        </p>
        <div class="tweet-info">
          <div class="tweet-top"><li class="user-name"><%= tweet.user.nickname %></li></div>
          <div class="tweet-top"><li class="create-time"><%= l tweet.created_at %></li></div>
          <div class="tweet-icon"><i class="fas fa-angle-down"></i></div>
        </div>
          <li class="user-task"><i class="fas fa-book-reader"></i>：<%= tweet.category.task %></li>
          <li class="study_time"><i class="fas fa-stopwatch"></i>：<%= tweet.hour_time %>h</li>
          <li class="study-text"><i class="fas fa-comments"></i><%= simple_format(tweet.text) %></li>
      </ul>
      <% end %>
     <%= paginate @tweets %>
    </div>
  </div>
</div>

app/views/tweets/_side_bar.html.erb
<div class="left-header">
  <% if user_signed_in? %>
  <ul class="user-info">
    <li><%= link_to current_user.nickname, "#", class: "user-nickname" %> </li>
    <li><i class="fas fa-user-circle"></i></li>
  </ul>
  <% end %>
</div>
<div class="left-main">
  <div class="left-stack">
    <%= render "tweets/study_record" %>
  </div>
<div class="container-task">
  <div class="left-task-contents">
    <%= render "categories/new" %>
  </div>
  <div id="left-task-lists">
    <%= render 'categories/index' %>
  </div>
</div>
  <div class="design-btn">
    <a href="/tweets/new" class="btn-square-little-rich">積み上げる</a>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.12"></script>

app/views/tweets/_side_runking.html.erb
  <div class="runking_contents">
    
      <div class="runking-best-contents">
        <form method="get" action="#" class="search_container">
          <input type="text" size="25" placeholder="　キーワード検索">
          <input type="submit" value="検索">
        </form>
      </div>
        <div class="best_user">
          <div class="box-title">積み上げランキング</div>
          <% @user_runking.each_with_index do |user,i| %>
            <p class="runking-list"><span><%= "#{i+1}位 #{user.nickname}" %></span></p>
          <% end %>
        </div>
          <ul class="follow-me">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
            <ul class="follow-me">
              <li><a href="https://twitter.com"></a></li>
              <li><a href="https://www.facebook.com"></a></li>
              <li><a href="https://plus.google.com"></a></li>
              <li><a href="https://www.youtube.com"></a></li>
              <li><a href="https://www.tumblr.com"></a></li>
           </ul>
      </div>
  </div>

app/views/tweets/_study_record.html.erb
<div class="record-view">
  <div class="all_time">
    <p class="study-log">あなたの総学習時間は、、、</p>
    <p class="time"><%= @study_hour %>時間です<p>
  </div>
</div>

app/views/tweets/_sub_header.html.erb
<div class="sub-header">
  <h1 class="sub-title"><%= link_to "futures", root_path %></h1>
  <ul class="header-lists">
    <%= link_to "新規登録", new_user_registration_path %>
    <%= link_to "ログイン", new_user_session_path %>
  </ul>
</div>

app/views/tweets/index.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<div class="wrapper">
  <div class="side-view">
    <%= render "side_bar" %>
  </div>
  <div class="main-view">
    <%= render "main_view" %>
  </div>
  <div class="runking-view">
    <%= render "side_runking" %>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="new-tweet">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
    <div class="contents-row-two">
      <div class="container-two">
        <%= form_with(model: @tweet_category, url: tweets_path, local: true) do |form| %>
          <h3>投稿する</h3>
          <%= form.collection_select(:category_id, @categories, :id, :task, {prompt: "タスクを選択して下さい"}, {} ) %>
          <%= form.text_area :hour_time, placeholder: "積み上げ時間を半角数字で入力してください。 小数点第一位まで可！", class: "time_area" %>
          <%= form.text_area :text, placeholder: "text", rows: "10" %>
          <%= form.submit "積み上げる" %>
        <% end %>
        <div class="top-return">
          <%= link_to "トップページへ戻る", root_path %>
        </div>
      </div>
    </div>
</div>

app/views/users/show.html.erb
<head>
  <link href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
</head>

<div class="profile-allcontainer">
  <div class="profile-header">

    <p class="profile-header-title">
      <i class="far fa-paper-plane"></i>
      <%= link_to "futures", root_path %>
    </p>
    <ul class="profile-header-list">
      <li><%= link_to "ホーム", root_path %><li>
      <li><%= link_to "積み上げる", new_tweet_path %><li>
      <li><%= link_to "ログアウト", destroy_user_session_path %></li>
    </ul>
  </div>
  <div class="profile-container">
    <div class="profile-box">
      <div class="profile-record">
        <div class="user-profile-name">
          <p><i class="fas fa-user-circle"></i></p>
          <p class="profile-name"><%= @user.nickname %></p>
        </div>
        <div class="user-profile-separator">
        </div>
        <div class="user-profile-item">
          <div class="user-item-container">
            <i class="fas fa-book"></i>
            <p class="profile-item"><%= @tweets_count %></p>
          </div>
          <p>総積み上げ数</p>
        </div>
        <div class="user-profile-separator">
        </div>
        <div class="user-profile-time">
          <div class="user-time-container">
            <i class="fas fa-medal"></i>
            <p class="profile-time"><%= @user_tweets %></p>
          </div>
          <p class="stydy-title">学習時間</p>
        </div>
      </div>
      <div class="top-contents">
        <div class="tweets-contents">
          <% @tweets.each do |tweet| %>
            <ul class="tweets-list">
              <p>
                <i class="fas fa-user-circle"></i>
              </p>
              <div class="tweet-info">
                <div class="tweet-top"><li class="user-name"><%= tweet.user.nickname %></li></div>
                <div class="tweet-top"><li class="create-time"><%= l tweet.created_at %></li></div>
                <div class="tweet-icon"><i class="fas fa-angle-down"></i></div>
              </div>
              <li class="user-task"><i class="fas fa-book-reader"></i>：<%= tweet.category.task %></li>
              <li class="study_time"><i class="fas fa-stopwatch"></i>：<%= tweet.hour_time %>h</li>
              <li class="study-text"><i class="fas fa-comments"></i><%= simple_format(tweet.text) %></li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
    <i class="far fa-calendar-alt"></i>
    <p class="chart-title">積み上げカレンダー</p>
    <div class="chart-box">
      <%= column_chart @tweets.group_by_day_of_week(:created_at, format: "%a").sum(:hour_time),xtitle: "Day", ytitle: "Time",width: "530px", height: "400px" %>
    </div>
    <div class="chart-box-responsive">
      <%= column_chart @tweets.group_by_day_of_week(:created_at, format: "%a").sum(:hour_time),xtitle: "Day", ytitle: "Time",width: "330px", height: "300px" %>
    </div>
  </div>
</div>
<style>
  html,body{background-color:#edf2fa;}
</style>